openapi: 3.0.0
info:
  title: 贷款管理系统 API
  version: 1.0.0
  description: 贷款管理系统的API文档

servers:
  - url: http://localhost:3000/api
    description: 开发环境

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: 用户ID
        username:
          type: string
          description: 用户名
        isAdmin:
          type: boolean
          description: 是否是管理员
        createdAt:
          type: string
          format: date-time
          description: 创建时间

    Loan:
      type: object
      properties:
        _id:
          type: string
          description: 贷款ID
        userId:
          type: string
          description: 用户ID
        name:
          type: string
          description: 贷款名称
        amount:
          type: number
          description: 贷款金额
        monthlyInterestRate:
          type: number
          description: 月利率(%)
        term:
          type: number
          description: 贷款期限(月)
          minimum: 1
          maximum: 360
        totalRepayment:
          type: number
          description: 总还款金额
        monthlyRepayment:
          type: number
          description: 月还款金额
        repaidAmount:
          type: number
          description: 已还金额
        type:
          type: string
          enum: [house, car, consumer, business, other]
          description: 贷款类型
        customType:
          type: string
          description: 自定义贷款类型
        bank:
          type: string
          enum: [ICBC, CCB, ABC, BOC, BOCOM, other]
          description: 银行
        customBank:
          type: string
          description: 自定义银行
        repaymentMethod:
          type: string
          enum: [equalPayment, equalPrincipal]
          description: 还款方式
        customRepaymentMethod:
          type: string
          description: 自定义还款方式
        status:
          type: string
          enum: [pending, approved, rejected, cancelled]
          description: 贷款状态
        createdAt:
          type: string
          format: date-time
          description: 创建时间
        updatedAt:
          type: string
          format: date-time
          description: 更新时间

    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          description: 状态码
        message:
          type: string
          description: 响应消息
        data:
          type: object
          description: 响应数据

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /users/register:
    post:
      tags:
        - 用户管理
      summary: 用户注册
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 注册成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  /users/login:
    post:
      tags:
        - 用户管理
      summary: 用户登录
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          token:
                            type: string
                          user:
                            $ref: '#/components/schemas/User'

  /loans:
    post:
      tags:
        - 贷款管理
      summary: 创建贷款
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - amount
                - monthlyInterestRate
                - term
                - type
                - bank
                - repaymentMethod
              properties:
                name:
                  type: string
                amount:
                  type: number
                monthlyInterestRate:
                  type: number
                term:
                  type: number
                type:
                  type: string
                  enum: [house, car, consumer, business, other]
                customType:
                  type: string
                bank:
                  type: string
                  enum: [ICBC, CCB, ABC, BOC, BOCOM, other]
                customBank:
                  type: string
                repaymentMethod:
                  type: string
                  enum: [equalPayment, equalPrincipal, interestFirst, bulletPayment, other]
                customRepaymentMethod:
                  type: string
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Loan'

  /loans/my:
    get:
      tags:
        - 贷款管理
      summary: 查看个人贷款
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Loan'

  /loans/{loanId}:
    put:
      tags:
        - 贷款管理
      summary: 更新贷款
      security:
        - bearerAuth: []
      parameters:
        - name: loanId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                amount:
                  type: number
                monthlyInterestRate:
                  type: number
                term:
                  type: number
                type:
                  type: string
                customType:
                  type: string
                bank:
                  type: string
                customBank:
                  type: string
                repaymentMethod:
                  type: string
                customRepaymentMethod:
                  type: string
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Loan'

  /loans/{loanId}/cancel:
    post:
      tags:
        - 贷款管理
      summary: 取消贷款
      security:
        - bearerAuth: []
      parameters:
        - name: loanId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 取消成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/Loan'

  /loans/all:
    get:
      tags:
        - 贷款管理
      summary: 查看所有贷款（管理员）
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Loan' 